<?php

declare(strict_types=1);

use App\Backend\Controllers\AuthController;
use App\Backend\Controllers\AdminAccountController;
use App\Backend\Controllers\AdminOrganizerChangeRequestController;
use App\Backend\Controllers\AdminSystemLogController;
use App\Backend\Controllers\AdminUserController;
use App\Backend\Controllers\DashboardController;
use App\Backend\Controllers\HomeController;
use App\Backend\Controllers\OrganizerAthleteQualificationController;
use App\Backend\Controllers\OrganizerCoachQualificationController;
use App\Backend\Controllers\OrganizerComplaintController;
use App\Backend\Controllers\OrganizerMatchResultController;
use App\Backend\Controllers\OrganizerPersonalInfoChangeRequestController;
use App\Backend\Controllers\OrganizerRankingController;
use App\Backend\Controllers\OrganizerRefereeController;
use App\Backend\Controllers\OrganizerScheduleController;
use App\Backend\Controllers\OrganizerTeamProfileController;
use App\Backend\Controllers\OrganizerTournamentController;
use App\Backend\Controllers\OrganizerVenueController;
use App\Backend\Controllers\RefereeAssignmentScheduleController;
use App\Backend\Controllers\RefereeIncidentReportController;
use App\Backend\Controllers\RefereeMatchSupervisionController;
use App\Backend\Core\Route\Router;

return static function (Router $router): void {
    $router->get('/', [HomeController::class, 'index']);

    $router->get('/login', [AuthController::class, 'showLogin']);
    $router->post('/login', [AuthController::class, 'login']);
    $router->post('/logout', [AuthController::class, 'logout'], ['auth']);

    $router->post('/api/auth/login', [AuthController::class, 'apiLogin']);
    $router->post('/api/auth/logout', [AuthController::class, 'apiLogout'], ['auth']);
    $router->get('/api/auth/me', [AuthController::class, 'apiMe'], ['auth']);

    $router->get('/dashboard', [DashboardController::class, 'index'], ['auth']);
    $router->get('/admin', [DashboardController::class, 'admin'], ['auth', 'role:ADMIN']);
    $router->get('/admin/users', [AdminAccountController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/nguoi-dung', [AdminUserController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/logs', [AdminSystemLogController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/xac-nhan-thong-tin-btc', [AdminOrganizerChangeRequestController::class, 'page'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/roles', [AdminAccountController::class, 'roles'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/accounts', [AdminAccountController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts', [AdminAccountController::class, 'store'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/accounts/{id}', [AdminAccountController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->add('PUT', '/api/admin/accounts/{id}', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('PATCH', '/api/admin/accounts/{id}', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts/{id}/update', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('DELETE', '/api/admin/accounts/{id}', [AdminAccountController::class, 'destroy'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts/{id}/delete', [AdminAccountController::class, 'destroy'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/users', [AdminUserController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/users/{id}', [AdminUserController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->add('PUT', '/api/admin/users/{id}', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('PATCH', '/api/admin/users/{id}', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/users/{id}/update', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/system-logs', [AdminSystemLogController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/system-logs/options', [AdminSystemLogController::class, 'options'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/system-logs/{id}', [AdminSystemLogController::class, 'show'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/organizer-change-requests', [AdminOrganizerChangeRequestController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/organizer-change-requests/{id}', [AdminOrganizerChangeRequestController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/organizer-change-requests/{id}/approve', [AdminOrganizerChangeRequestController::class, 'approve'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/organizer-change-requests/{id}/reject', [AdminOrganizerChangeRequestController::class, 'reject'], ['auth', 'role:ADMIN']);

    $router->get('/ban-to-chuc', [DashboardController::class, 'organizer'], ['auth', 'role:BAN_TO_CHUC,ADMIN']);
    $router->get('/ban-to-chuc/giai-dau', [OrganizerTournamentController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/doi-bong', [OrganizerTeamProfileController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/trong-tai', [OrganizerRefereeController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/huan-luyen-vien', [OrganizerCoachQualificationController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/van-dong-vien', [OrganizerAthleteQualificationController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/san-dau', [OrganizerVenueController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/lich-thi-dau', [OrganizerScheduleController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/khieu-nai', [OrganizerComplaintController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/ket-qua', [OrganizerMatchResultController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/xep-hang', [OrganizerRankingController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/xac-nhan-thong-tin-ca-nhan', [OrganizerPersonalInfoChangeRequestController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments', [OrganizerTournamentController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments', [OrganizerTournamentController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/update', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/publish', [OrganizerTournamentController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/registrations', [OrganizerTournamentController::class, 'registrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/open', [OrganizerTournamentController::class, 'openRegistrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/close', [OrganizerTournamentController::class, 'closeRegistrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/{registrationId}/approve', [OrganizerTournamentController::class, 'approveRegistration'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/{registrationId}/reject', [OrganizerTournamentController::class, 'rejectRegistration'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/teams', [OrganizerTeamProfileController::class, 'all'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/teams/{teamId}', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/teams/{teamId}', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/teams/{teamId}/update', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/teams', [OrganizerTeamProfileController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/teams/{teamId}', [OrganizerTeamProfileController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/teams/{teamId}/cancel-participation', [OrganizerTeamProfileController::class, 'cancelParticipation'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referees', [OrganizerRefereeController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees', [OrganizerRefereeController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-matches', [OrganizerRefereeController::class, 'matches'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-leaves', [OrganizerRefereeController::class, 'leaves'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referee-assignments', [OrganizerRefereeController::class, 'assign'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referees/{refereeId}', [OrganizerRefereeController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees/{refereeId}/assignments', [OrganizerRefereeController::class, 'assign'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees/{refereeId}/leave', [OrganizerRefereeController::class, 'leave'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coaches', [OrganizerCoachQualificationController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coaches/{coachId}', [OrganizerCoachQualificationController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/approve', [OrganizerCoachQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/cancel-qualification', [OrganizerCoachQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/cancel', [OrganizerCoachQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/athletes', [OrganizerAthleteQualificationController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/athletes/{athleteId}', [OrganizerAthleteQualificationController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/approve-qualification', [OrganizerAthleteQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/approve', [OrganizerAthleteQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/cancel-qualification', [OrganizerAthleteQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/cancel', [OrganizerAthleteQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/venues', [OrganizerVenueController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues', [OrganizerVenueController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/update', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/deactivate', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/remove', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/delete', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/schedules/tournaments', [OrganizerScheduleController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/schedule', [OrganizerScheduleController::class, 'summary'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/groups', [OrganizerScheduleController::class, 'groups'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups', [OrganizerScheduleController::class, 'storeGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'group'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups/{groupId}/update', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'deleteGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups/{groupId}/delete', [OrganizerScheduleController::class, 'deleteGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/matches', [OrganizerScheduleController::class, 'matches'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches', [OrganizerScheduleController::class, 'storeMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'match'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches/{matchId}/update', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'deleteMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches/{matchId}/delete', [OrganizerScheduleController::class, 'deleteMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/complaints', [OrganizerComplaintController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/complaints/{complaintId}', [OrganizerComplaintController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/receive', [OrganizerComplaintController::class, 'receive'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/accept', [OrganizerComplaintController::class, 'receive'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/reject', [OrganizerComplaintController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/resolve', [OrganizerComplaintController::class, 'resolve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/no-process', [OrganizerComplaintController::class, 'noProcess'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/ignore', [OrganizerComplaintController::class, 'noProcess'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-results', [OrganizerMatchResultController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/results', [OrganizerMatchResultController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/adjust', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/update', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/adjust', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/update', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/publish', [OrganizerMatchResultController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/publish', [OrganizerMatchResultController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/rankings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/rankings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/rankings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/standings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/personal-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/profile-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/personal-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/profile-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/tournaments/{id}/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/standings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/personal-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/profile-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/personal-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/profile-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'destroy'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/delete', [OrganizerTournamentController::class, 'destroy'], ['auth', 'role:BAN_TO_CHUC']);

    $router->get('/trong-tai', [DashboardController::class, 'referee'], ['auth', 'role:TRONG_TAI,ADMIN']);
    $router->get('/trong-tai/lich-phan-cong', [RefereeAssignmentScheduleController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/trong-tai/giam-sat', [RefereeMatchSupervisionController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignment-schedule', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/match-assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/tournaments-of-me', [RefereeAssignmentScheduleController::class, 'tournaments'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/venues-of-me', [RefereeAssignmentScheduleController::class, 'venues'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-report-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/reportable-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-reports', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incidents', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-reports/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incidents/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignment-schedule/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/match-assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}', [RefereeAssignmentScheduleController::class, 'showMatch'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}/detail', [RefereeAssignmentScheduleController::class, 'matchDetail'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}/supervision', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/supervision/matches/{matchId}', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/participants', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/assignments/{assignmentId}/confirm', [RefereeAssignmentScheduleController::class, 'confirm'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/assignments/{assignmentId}/decline', [RefereeAssignmentScheduleController::class, 'decline'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/tournaments-of-me', [RefereeAssignmentScheduleController::class, 'tournaments'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/venues-of-me', [RefereeAssignmentScheduleController::class, 'venues'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-report-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/reportable-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-reports', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incidents', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-reports/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incidents/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/assignments/{assignmentId}/confirm', [RefereeAssignmentScheduleController::class, 'confirm'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/assignments/{assignmentId}/decline', [RefereeAssignmentScheduleController::class, 'decline'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignment-schedule', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/match-assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignment-schedule/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/match-assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}', [RefereeAssignmentScheduleController::class, 'showMatch'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}/detail', [RefereeAssignmentScheduleController::class, 'matchDetail'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}/supervision', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/supervision/matches/{matchId}', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/participants', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->get('/huan-luyen-vien', [DashboardController::class, 'coach'], ['auth', 'role:HUAN_LUYEN_VIEN,ADMIN']);
    $router->get('/van-dong-vien', [DashboardController::class, 'athlete'], ['auth', 'role:VAN_DONG_VIEN,ADMIN']);
    $router->get('/khan-gia', [DashboardController::class, 'spectator'], ['auth', 'role:KHAN_GIA,ADMIN']);
};
